# Results

## Investigate contents of popular playlists.
```{r}
artists <- all_tracks %>% distinct(artist_name, artist_uri)
tracks <- all_tracks %>% distinct(track_name, track_uri)
```
### Artists
```{r}
top_30_artists <- all_tracks %>% group_by(artist_name) %>% 
  summarise(n = n()) %>% 
  top_n(30, n) %>%
  arrange(desc(n)) 


top_30_artists %>%
  ggplot(aes(x = n, y = fct_reorder(artist_name, n))) +
  geom_point() + 
  xlab("Track Count") +
  ylab("Artist Name")
```

  Show the distribution of the number of tracks each artist has in all tracks:

```{r}
all_tracks %>% group_by(artist_name) %>% 
  mutate(n = n()) %>% 
  ggplot(aes(x = "all artists", n)) + 
  geom_boxplot()+
  stat_summary(geom = "errorbar", fun.min = mean, fun = mean, fun.max = mean, width = .75, linetype = "dashed")+
  ggtitle("How many tracks each artist has in all tracks of popular playlists?") + 
  ylab("Track Count")

all_tracks %>% group_by(artist_name) %>% 
  mutate(n = n()) %>% 
  ggplot(aes(n)) + geom_histogram(color = "grey", fill = "lightBlue", 
                 binwidth = 25, boundary=0) 
```
 
### Tracks
```{r, warning=FALSE}
track_uri_name <- distinct(all_tracks, track_uri, track_name, artist_name)

df2 <- all_tracks %>% group_by(track_name) %>% mutate(count=n(), track_artist = paste(track_name, artist_name, sep=" @ "))

  
top_30_tracks <- all_tracks %>% group_by(track_uri) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count)) %>%
  top_n(30) 


top_30_tracks[c('track', 'artist')] <- track_uri_name[match(top_30_tracks$track_uri, track_uri_name$track_uri), c('track_name', 'artist_name')]
#track_uri_name %>% filter(track_uri %in% top_30_tracks$track_uri) %>% select(track_name, artist_name)

tr_30 <- top_30_tracks
tr_30$track[startsWith(tr_30$track, "CAN'T STOP THE FEELING")] <-  "CAN'T STOP THE FEELING!"
tr_30 %>%
  ggplot(aes(x = count, y = fct_reorder(as.factor(track), count), fill=count)) +
  geom_bar(stat = "identity") + 
  xlab("Number of Tracks") +
  ylab("Track Name") 
  

```