# Conclusion

Based on our graphical analysis, we conclude that the popularity of playlists are not determined by the popularity of its tracks or albums, although the popularity of artists can be a contributor since most of the popular playlists have tracks from popular artists. Tracks in these popular playlists have a wide range and are not concentrated on a small set of hit records as hypothesized. 

The analysis of audio features of tracks in popular playlists show that most of them are of moderately high danceability and energy with moderately low liveness and acousticness. This finding reflects the current trend of electronic and hip-hop music which have those features and the unpopularity of acoustic and live music. It can lead to further investigation on the occassion where most people are listening to music. For example, are they listening to slow songs alone or at a party streaming dance music? 

The time series of the audio features of tracks in the ordering of streaming a whole super popular playlist indicates that these playlists mostly have tracks whose audio features are constantly changing. Even from one song to another, it can shift to the next that has completely different audio features. This variety demonstrates the creators of the playlists understand that music should be constanstly changing in order to avoid listeners' loss of interest. The combination also shows that although the acousticness and liveness are mostly low, super popular playlists will sometimes have spikes in them, meaning creators inserting tracks that are more acoustic and like a live performance. These spikes also illustrate the pointing of mixing up tracks of different audio features in the reverse direction. 

The limitations of this project are downloaded from the spotify's open million playlist chanllenge. These playlists are created between 2010 and 2017, so they might be outdated. Furthermore, spotify's API does not discuss how they calculate the popularity score of a track. It is unclear if the score is for current streaming statistics or accumulative statistics. Some apparently popular tracks have popularity scores of zero. This might affect the accuracy of this project in terms of the contribution of the popularity of the playlist's content. 